/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from './routes/workspace.$workspaceId.index'
import { Route as WorkspaceWorkspaceIdUsersRouteImport } from './routes/workspace.$workspaceId.users'
import { Route as WorkspaceWorkspaceIdProjectsProjectIdRouteImport } from './routes/workspace.$workspaceId.projects.$projectId'
import { Route as WorkspaceWorkspaceIdUsersUserIdRouteImport } from './routes/workspace.$workspaceId.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdUsersRoute =
  WorkspaceWorkspaceIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdProjectsProjectIdRoute =
  WorkspaceWorkspaceIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdUsersUserIdRoute =
  WorkspaceWorkspaceIdUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => WorkspaceWorkspaceIdUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/users': typeof WorkspaceWorkspaceIdUsersRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/projects/$projectId': typeof WorkspaceWorkspaceIdProjectsProjectIdRoute
  '/workspace/$workspaceId/users/$userId': typeof WorkspaceWorkspaceIdUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$workspaceId/users': typeof WorkspaceWorkspaceIdUsersRouteWithChildren
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/projects/$projectId': typeof WorkspaceWorkspaceIdProjectsProjectIdRoute
  '/workspace/$workspaceId/users/$userId': typeof WorkspaceWorkspaceIdUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/users': typeof WorkspaceWorkspaceIdUsersRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/projects/$projectId': typeof WorkspaceWorkspaceIdProjectsProjectIdRoute
  '/workspace/$workspaceId/users/$userId': typeof WorkspaceWorkspaceIdUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/users'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/projects/$projectId'
    | '/workspace/$workspaceId/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$workspaceId/users'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/projects/$projectId'
    | '/workspace/$workspaceId/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/users'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/projects/$projectId'
    | '/workspace/$workspaceId/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/users': {
      id: '/workspace/$workspaceId/users'
      path: '/users'
      fullPath: '/workspace/$workspaceId/users'
      preLoaderRoute: typeof WorkspaceWorkspaceIdUsersRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/projects/$projectId': {
      id: '/workspace/$workspaceId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspace/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/users/$userId': {
      id: '/workspace/$workspaceId/users/$userId'
      path: '/$userId'
      fullPath: '/workspace/$workspaceId/users/$userId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdUsersUserIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdUsersRoute
    }
  }
}

interface WorkspaceWorkspaceIdUsersRouteChildren {
  WorkspaceWorkspaceIdUsersUserIdRoute: typeof WorkspaceWorkspaceIdUsersUserIdRoute
}

const WorkspaceWorkspaceIdUsersRouteChildren: WorkspaceWorkspaceIdUsersRouteChildren =
  {
    WorkspaceWorkspaceIdUsersUserIdRoute: WorkspaceWorkspaceIdUsersUserIdRoute,
  }

const WorkspaceWorkspaceIdUsersRouteWithChildren =
  WorkspaceWorkspaceIdUsersRoute._addFileChildren(
    WorkspaceWorkspaceIdUsersRouteChildren,
  )

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdUsersRoute: typeof WorkspaceWorkspaceIdUsersRouteWithChildren
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdProjectsProjectIdRoute: typeof WorkspaceWorkspaceIdProjectsProjectIdRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdUsersRoute: WorkspaceWorkspaceIdUsersRouteWithChildren,
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdProjectsProjectIdRoute:
    WorkspaceWorkspaceIdProjectsProjectIdRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
